### PR TITLE
add labeler rules for labeler bot for severity, update bug with missing severity option

### PR DESCRIPTION
**Pull request by Omzig**

### CODE REVIEW

**Review by MikeShepard — APPROVED** [review]

**Comment by adamdriscoll** [comment]
Neat!

**Comment by Omzig** [comment]
@adamdriscoll, i cannot see your settings, did you add the bot?

I clicked the add, not sure where you have to approve it.

https://probot.github.io/apps/issuelabeler/

image

**Comment by adamdriscoll** [comment]
I added the bot just now. How does it look now?

**Comment by Omzig** [comment]
its working, but i need to rename the template:

image

- https://github.com/ironmansoftware/issues/issues/3252

**Comment by Omzig** [comment]
@adamdriscoll , i filed a bug: 
- https://github.com/riyadhalnur/issuelabeler/issues/65

**Pull request merged**
